Fix ClassNotFoundException for TelephonyDisplayInfo
TelephonyDisplayInfo was introduced in SDK 30. Users who use TelephonyService
in tests will see the error:
java.lang.ClassNotFoundException: android.telephony.TelephonyDisplayInfo
unless they upgrade their compile/target SDK to 30.

To avoid breaking existing tests for users who do not upgrade, use Object
instead of TelephonyDisplayInfo for method signatures and member variables.

Fixes #5968

PiperOrigin-RevId: 336339416