Use a mock ContextHubClientCallback in ShadowContextHubManagerTest
This is to fix java.lang.NoClassDefFoundError: android/hardware/location/ContextHubClientCallback when running
ShadowContextHubManagerTest in Gradle environments.

When a mock is used, it defers subclassing ContextHubClientCallback
until runtiem instead of compile time.

PiperOrigin-RevId: 671888654