Fixes an error when mocking a generic method with Mockk
When mocking a generic method with Mockk under the Robolectric classloader, the following exception is thrown:

```
io.mockk.MockKException: Class cast exception happened.
    Probably type information was erased.
...
Caused by:
        java.lang.ClassCastException: class Foo cannot be cast to class Foo (Foo is in unnamed module of loader 'app'; Foo is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @)
```

Related issues: https://github.com/mockk/mockk/issues/606, https://github.com/robolectric/robolectric/issues/5994.

A self-contained demo project https://github.com/ogolberg/robolectric-mockk-compat ([github actions](https://github.com/ogolberg/robolectric-mockk-compat/actions)): note how overriding the runner to exclude `io.mockk.proxy.` instead of the blanket `io.mockk.` fixes the test.