Fix AssociationInfoBuilderTest on android V.
getLastTimeConnectedMs return type has changed in latest compile SDK
resulting in a NoSuchMethodError.
Use reflection to access it instead.

PiperOrigin-RevId: 646649282