Remove dependency on com.google.android.collect.Lists from BroadcastReceiverData.
These classes are now obsolete since the diamond operator plus Robolectric framework really shouldn't be depending on AOSP code.

This causes a java.lang.NoClassDefFoundError: com/google/android/collect/Lists error if the manifest is parsed early outside of a context using the AOSP classloader.

Note: We parse the manifest early as our build system requires us to reconcile ids across all library projects with resources in the transative build closure.