Throw NameNotFoundException from Context.createPackageContext for non-existing packages.
Right now this is what happens:

java.lang.RuntimeException: android.os.RemoteException: non.exist.package.name
	at android.os.RemoteException.rethrowFromSystemServer(RemoteException.java:61)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1992)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2100)
	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2087)
Caused by: android.os.RemoteException: non.exist.package.name
	at org.robolectric.shadows.ShadowActivityThread$1.invoke(ShadowActivityThread.java:53)
	at com.sun.proxy.$Proxy20.getApplicationInfo(Unknown Source)
	at android.app.ActivityThread.$$robo$$android_app_ActivityThread$getPackageInfo(ActivityThread.java:1987)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java)
	at android.app.ContextImpl.$$robo$$android_app_ContextImpl$createPackageContextAsUser(ContextImpl.java:2100)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java)
	at android.app.ContextImpl.$$robo$$android_app_ContextImpl$createPackageContext(ContextImpl.java:2087)
	at android.app.ContextImpl.createPackageContext(ContextImpl.java)

PiperOrigin-RevId: 230434769