Fixed running error when using the biometrics API (android.hardware.biometrics.CryptoObject#getOpId())
Added shadow for android.hardware.biometrics.CryptoObject with method getOpId() to return default value to avoid calling deeper into the API where Cipher.getCurrentSpi() is invoked which causes a crash (NoSuchMethodError).