Fix NoClassDefFoundError ClassInfo error.
Switching from shadowClass getMethod() to getDeclaredMethods() caused
lambdas in ShadowDisplay to be resolved; since DisplayInfo doesn't exist
in API 16, we can't use it in a method signature. Create internal
DisplayConfig with the same fields.