Fixed negative ids that cause ArrayOutOfBounds.
When there are more than 32k resources with same type and package, tests crash with something like that:
java.lang.ArrayIndexOutOfBoundsException: Index -32362 out of bounds for length 34479
Commit fixes signed short overflow in this scenario.