Depend on junit-dep instead of junit
The junit jar (vs the junit-dep jar) contains several hamcrest classes.
Since we include hamcrest-core anyway, we should be using junit-dep
(which does not contain any hamcrest classes).  junit-4.8.2 contains an
old (<1.2) version of hamcrest.  This can cause problems (specifically,
"java.lang.NoSuchMethodError:
org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V")
if someone uses a library that contains custom matchers extending >1.2
org.hamcrest.Matcher but has Robolectric on their classpath before
hamcrest-core, as the org.hamcrest.MatcherAssert contained in
junit-4.8.2 is not compatible with org.hamcrest.Matcher contained in
hamcrest-core-1.2