Fix test crashes due to missing Backdropframerenderer.
PR #8917 caused the following crash for any test running on SDKs < 23
```
java.lang.NoClassDefFoundError: com/android/internal/policy/BackdropFrameRenderer
```

BackdropFrameRenderer was only introduced in SDK 24.
This commit fixes the crash by adding a SDK if check before running the offending code.

PiperOrigin-RevId: 618330430