Use Object to replace GnssAntennaInfo.Listener at ShadowLocationManager
The GnssAntennaInfo and GnssAntennaInfo.Listener is added at API 30, and
it will cause NoClassDefFoundError when running Robolectric with target
SDK less than 30, for example 29.

Signed-off-by: utzcoz <utzcoz@outlook.com>