Fix `NoClassDefFoundError` in `ShadowRemoteViewsAdapterTest`
`ShadowRemoteViewsAdapterTest` is failing on `master` following the latest merge of `google` into `master`.
`RemoteAdapterConnectionCallback` may not be available at compile time, causing a `NoClassDefFoundError`.
This commit switches the no-op implementation with a mock.